--- 
- name: tomcat installation
  hosts: webservers
  become: true

  tasks:
    - name: installing java in RedHat
      yum:
        name: java 
        state: installed
      when: ansible_os_family == "RedHat"
  
    - name: installing java in Debion
      yum: 
        name: default-jdk
        state: present
      when: ansible_os_family == "Debion"
    
    - name: downlod tomcat
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.72/bin/apache-tomcat-8.5.72.tar.gz
        dest: /opt
       
    - name: extracting tar file
      unarchive:
        src: /opt/apache-tomcat-8.5.72.tar.gz
        dest: /opt
        remote_src: True     

    - name: change permissions
      file:
         path: /opt/apache-tomcat-8.5.72/bin/startup.sh
         mode: "0777"

    - name: Run Tomcat
      shell: nohup ./startup.sh
      args:
          chdir: /opt/apache-tomcat-8.5.72/bin
       
